[package]
name = "lib-rs"
version = "0.1.0"
authors = ["Aofusa <5000enPCinAOFUSA@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.16.0"

[lib]
name = "embed"
crate-type = ["dylib", "cdylib"]
